package com.ruhuna.event_ticket_management_system.exception;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

@ControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(RuntimeException.class)
    public ResponseEntity<Object> handleRuntimeException(RuntimeException ex) {
        Map<String, Object> errorDetails = new HashMap<>();
        errorDetails.put("timestamp", LocalDateTime.now());
        errorDetails.put("message", ex.getMessage());

        if (ex.getMessage().contains("Username is already taken")) {
            return new ResponseEntity<>(errorDetails, HttpStatus.CONFLICT); // 409
        } else if (ex.getMessage().contains("Email is already in use")) {
            return new ResponseEntity<>(errorDetails, HttpStatus.CONFLICT); // 409
        } else if (ex.getMessage().contains("Invalid username or password")) {
            return new ResponseEntity<>(errorDetails, HttpStatus.UNAUTHORIZED); // 401
        } else if (ex.getMessage().contains("Role is not found")) {
            return new ResponseEntity<>(errorDetails, HttpStatus.INTERNAL_SERVER_ERROR); // 500
        }

        return new ResponseEntity<>(errorDetails, HttpStatus.BAD_REQUEST); // fallback
    }
}
